FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy only package files first
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# Enable polling for live updates inside Docker
ENV CHOKIDAR_USEPOLLING=true

# Expose React's default port
EXPOSE 3000

# Start the dev server
CMD ["npm", "start"]
