routes:
  - path: "/"
    component: "HomePage"
  - path: "/ratesanddates"
    component: "RatesAndDates"
  - path: "/rentatrailer"
    component: "RentATrailer"
  - path: "/about"
    component: "AboutPage"
  - path: "/contact"
    component: "ContactPage"
  - path: "/form"
    component: "FormPage"