routes:
  - path: "/"
    component: "HomePage"
  - path: "/ratesanddates"
    component: "RatesAndDates"
  - path: "/rentatrailer"
    component: "RentATrailer"
  - path: "/about"
    component: "AboutPage"
  - path: "/contact"
    component: "ContactPage"
  - path: "/form"
    component: "FormPage"
  - path: "/confirmation"
    component: "ConfirmationPage"
  - path: "/book-appointment"
    component: "BookAppointment"
  - path: "/termsofservice"
    component: "TermsOfService"